### ISSUE TITLE
Hey, I think I can add something to the code to make it more better.

### ISSUE THREAD

**Issue by jha-niraj** [nirajjha3110/Testing-PR#1]
Like an if-else statement to greet people on the basis of their age.

**Comment by nirajjha3110** [comment]
Hey, can you please do it today.

**Comment by jha-niraj** [comment]
Yeah I can. I am doing it right now. I will let you know when I am done.

**Comment by nirajjha3110** [comment]
Okk

**Comment by nirajjha3110** [comment]
Great.
